env: "development"

http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s

postgresql:
  host: "localhost"
  port: "8823"
  user: "postgres"
  password: "postgres"
  database: "postgres"
  sslmode: "disable"