services:
  db:
    image: postgres:latest
    restart: on-failure

    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /tmp/pgdata

    ports:
      - "8823:5432"
    tmpfs:
      - /tmp/pgdata    
    volumes:
      - ./postgres/01_schema_init.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./postgres/init_scripts/category_functions.sql:/docker-entrypoint-initdb.d/02_functions.sql
      - ./postgres/init_scripts/test_data.sql:/docker-entrypoint-initdb.d/03_test_data.sql


#volumes:
#  postgres-data:
